# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:          GetBeauty
email:          getbeauty.developers@gmail.com
description:    GET BEAUTY
url:            http://www.getbeauty.us
baseurl:        ""
css_url:        "/static/css"
img_url:        "/static/images"
js_url:         "/static/js"
bootstrap_url:  "/static/bootstrap"
disqus:         mintakson
share:          true
dropcap:	      true
logo_path:      "/content/invision-logo.png"

# Build settings
markdown:       kramdown
highlighter:    pygments
timezone:       America/Los_Angeles
future:         true
rouge:          pygments
paginate:       5
paginate_path:  "page:num"
permalink:      /blog/:title/

# Owner/author information
owner:
  name:           Get Beauty
  email:          Get Beauty@gmail.com

# google:
#   analytics:      UA-68684835-2

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

gems:
  - jemoji
  - jekyll-paginate

atom:
  buildCommand:
    - jekyll
    - build
    - --drafts
    - --option
    - --this
  buildEnv:
    JEKYLL_ENV: development
  postDirs:
  defaultPostDir: _drafts
